local C, F, L = unpack(select(2, ...))

local client = GetLocale()

-- Default English
L["AutoFade"] = "Auto fade"
L["AutoHide"] = "Auto hide"
L["ShowTitle"] = "Show title"
L["Minimize"] = "Minimize all"
L["Maximize"] = "Maximize all"
L["To"] = "To"
L["From"] = "From"
L["FontSize"] = "Font size"
L["Width"] = "Width"
L["Height"] = "Height"
L["Chat"] = "Chat"

if client == "frFR" then -- French
	L["AutoFade"] = "Fondu automatique"
	L["AutoHide"] = "Cacher automatiquement"
	L["ShowTitle"] = "Montrer le titre"
	L["Minimize"] = "Tout minimiser"
	L["Maximize"] = "Tout agrandir"
	L["To"] = "À"
	L["From"] = "De"
	L["FontSize"] = "Taille police"
	L["Width"] = "Largeur"
	L["Height"] = "Hauteur"
	L["Chat"] = "Chat"
elseif client == "deDE" then -- German
	L["AutoFade"] = "Autom. verblassen"
	L["AutoHide"] = "Autom. verstecken"
	L["ShowTitle"] = "Zeige Titel"
	L["Minimize"] = "Minimiere alle"
	L["Maximize"] = "Maximiere alle"
	L["To"] = "Zu"
	L["From"] = "Von"
	L["FontSize"] = "Schriftgröße"
	L["Width"] = "Breite"
	L["Height"] = "Höhe"
	L["Chat"] = "Chat"
elseif client == "koKR" then -- Korean
	L["AutoFade"] = "자동 열기"
	L["AutoHide"] = "자동 숨기기"
	L["ShowTitle"] = "제목 보이기"
	L["Minimize"] = "모두 최소화"
	L["Maximize"] = "모두 최대화"
	L["To"] = "받은 사람"
	L["From"] = "보낸 사람"
	L["FontSize"] = "글꼴 크기"
	L["Width"] = "폭"
	L["Height"] = "높이"
	L["Chat"] = "채팅"
elseif client == "ruRU" then -- Russian
	L["AutoFade"] = "Auto fade"
	L["AutoHide"] = "Auto hide"
	L["ShowTitle"] = "Show title"
	L["Minimize"] = "Minimize all"
	L["Maximize"] = "Maximize all"
	L["To"] = "To"
	L["From"] = "From"
	L["FontSize"] = "Font size"
	L["Width"] = "Width"
	L["Height"] = "Height"
	L["Chat"] = "Chat"
elseif client == "esES" then -- Spanish
	L["AutoFade"] = "Auto fade"
	L["AutoHide"] = "Ocultar Automaticamente"
	L["ShowTitle"] = "Mostrar Nombre"
	L["Minimize"] = "Minimizar todas las ventanas"
	L["Maximize"] = "Maximizar todas las ventanas"
	L["To"] = "Para"
	L["From"] = "De"
	L["FontSize"] = "Tamaño de la fuente"
	L["Width"] = "Anchura"
	L["Height"] = "Altura"
	L["Chat"] = "Chat"
elseif client == "zhTW" then -- Taiwanese
	L["AutoFade"] = "Auto fade"
	L["AutoHide"] = "Auto hide"
	L["ShowTitle"] = "Show title"
	L["Minimize"] = "Minimize all"
	L["Maximize"] = "Maximize all"
	L["To"] = "To"
	L["From"] = "From"
	L["FontSize"] = "Font size"
	L["Width"] = "Width"
	L["Height"] = "Height"
	L["Chat"] = "Chat"
end